#!/usr/bin/python3

DOMAIN = "mintsources"
PATH = "/usr/share/linuxmint/locale"

import os, gettext, sys
sys.path.append('/usr/lib/linuxmint/common')
import additionalfiles

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=pkexec mintsources
Icon=mintsources
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=GNOME;GTK;System;Settings;X-GNOME-SystemSettings;X-GNOME-Settings-Panel;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
X-GNOME-Settings-Panel=software-properties
MimeType=text/x-apt-sources-list;
X-KDE-SubstituteUID=true
NotShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/mintsources.desktop", prefix, _("Software Sources"), _("Configure the sources for installable software and updates"), suffix)

prefix = "[Desktop Entry]\n"

suffix= """Exec=pkexec mintsources
Icon=mintsources
Terminal=false
Type=Application
Encoding=UTF-8
MimeType=text/x-apt-sources-list;
Categories=Qt;KDE;Settings;
X-KDE-StartupNotify=false
OnlyShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/kde4/mintsources.desktop", prefix, _("Software Sources"), _("Configure the sources for installable software and updates"), suffix, genericName=_("Configure the sources for installable software and updates"))
