#!/bin/bash

intltool-extract --type=gettext/glade usr/lib/linuxmint/mintSources/mintSources.glade

xgettext --language=Python --keyword=_ --output=mintsources.pot \
  usr/lib/linuxmint/mintSources/mintSources.py \
  usr/lib/linuxmint/mintSources/ppa_browser.py \
  usr/lib/linuxmint/mintSources/foreign_packages.py \
  usr/lib/linuxmint/mintSources/mintSources.glade.h \
  usr/bin/software-sources \
  usr/bin/add-apt-repository \
  generate_desktop_files
xgettext --language=PolkitPolicy --its=polkit.its --output=mintsources.pot --join-existing usr/share/polkit-1/actions/*.policy

rm -f usr/lib/linuxmint/mintSources/mintSources.glade.h
